Conflict view
wpz2023/room-booking-system pull request #32
Opened 2023-04-27 19:10 UTC by Denwiliusz27

![image](https://user-images.githubusercontent.com/70195490/234967233-9b2a2892-eaac-4db3-af4f-7d12ddb91358.png)
![image](https://user-images.githubusercontent.com/70195490/234967339-982bd6cd-4dc6-4bd0-a771-b9f8dfb45775.png)

2023-04-27 19:13 UTC, bestemic commented
Backend changes looks good

2023-04-28 08:45 UTC, clooux requested changes

2023-04-28 08:45 UTC, clooux commented on frontend/src/components/ConflictPopUp.tsx
> +    const changeClasstypeName = (classType: Map<string, string>) => {
isn't this function used in other file? if so move it to separate ts file

2023-05-02 14:16 UTC, bestemic approved these changes

2023-05-02 14:18 UTC, clooux approved these changes
doesn't look good to me

2023-05-02 14:22 UTC, merged